---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller
rules:
  - apiGroups:
      - supercaracal.example.com
    resources:
      - foobars
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller
subjects:
  - kind: ServiceAccount
    name: controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller
rules:
  - apiGroups:
      - supercaracal.example.com
    resources:
      - foobars
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foobar-controller
      app.kubernetes.io/part-of: supercaracal.example.com
      app.kubernetes.io/component: kubernetes-custom-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foobar-controller
        app.kubernetes.io/part-of: supercaracal.example.com
        app.kubernetes.io/component: kubernetes-custom-controller
    spec:
      serviceAccountName: controller
      containers:
        - name: main
          image: ghcr.io/supercaracal/kubernetes-controller-template:latest
          env:
            - name: TZ
              value: "Asia/Tokyo"
            - name: SELF_NAMESPACE
              value: "default"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            readOnlyRootFilesystem: true
