---
# @see https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Test
on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: Test
    timeout-minutes: 15
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go-ver: ["1.17"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-ver }}

      - name: Get dependencies
        run: |
          go install golang.org/x/lint/golint@latest
          go install k8s.io/code-generator/...@latest

      - name: Generate several codes
        run: make codegen

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Lint docker image
        run: make lint-image
        if: runner.os == 'Linux'

      - name: Build docker image
        run: make build-image
        if: runner.os == 'Linux'
