---
# @see https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# @see https://github.com/actions/virtual-environments
name: Test
on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: Test
    timeout-minutes: 20
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go-ver: ["1.17"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-ver }}

      - name: Get dependencies
        run: |
          go install golang.org/x/lint/golint@latest
          go install k8s.io/code-generator/...@latest

      - name: Generate several codes
        run: make codegen

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Lint container image
        run: make lint-image
        if: runner.os == 'Linux'

      - name: Create cluster with Kind
        run: kind create cluster
        if: runner.os == 'Linux'

      - name: Apply manifests
        run: make apply-manifests
        if: runner.os == 'Linux'

      - name: Build container image
        run: make build-image
        if: runner.os == 'Linux'

      - name: Start port forwarding for container registry
        run: make port-forward &
        if: runner.os == 'Linux'

      - name: Push container image
        run: make push-image
        if: runner.os == 'Linux'

      - name: Waiting for the pod to be ready
        run: sleep 30
        if: runner.os == 'Linux'

      - name: Get pod logs
        run: |
          name=$(kubectl --context=kind-kind get pods -o json | jq -r '.items[] | .metadata.name' | grep controller)
          kubectl --context=kind-kind logs $name
        if: runner.os == 'Linux'
