---
# @see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# @see https://github.com/actions/virtual-environments
name: Test
on:
  push:
    branches:
      - "*"
defaults:
  run:
    shell: bash
  go-ver: "1.17"
  os: "ubuntu-latest"
jobs:
  prepare:
    name: Prepare
    timeout-minutes: 5
    runs-on: ${{ defaults.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
  build-code:
    name: Build Code
    needs: prepare
    timeout-minutes: 10
    runs-on: ${{ defaults.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ defaults.go-ver }}

      - name: Check out paths
        id: go-cache-paths
        run: |
          echo "::set-output name=go-cache::$(go env GOCACHE)"
          echo "::set-output name=go-mod-cache::$(go env GOMODCACHE)"

      - name: Cache GOCACHE
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-cache }}
          key: ${{ runner.os }}-go-cache-${{ hashFiles('go.sum') }}

      - name: Cache GOMODCACHE
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod-cache }}
          key: ${{ runner.os }}-go-mod-cache-${{ hashFiles('go.sum') }}

      - name: Get dependencies
        run: |
          go install golang.org/x/lint/golint
          go install k8s.io/code-generator/...

      - name: Generate several codes
        run: make codegen

      - name: Build
        run: make build
  test-code:
    name: Test Code
    needs: build-code
    timeout-minutes: 10
    runs-on: ${{ defaults.os }}
    steps:
      - name: Test
        run: make test
  lint-code:
    name: Lint Code
    needs: build-code
    timeout-minutes: 10
    runs-on: ${{ defaults.os }}
    steps:
      - name: Lint
        run: make lint
  lint-image:
    name: Lint Image
    needs: prepare
    timeout-minutes: 10
    runs-on: ${{ defaults.os }}
    steps:
      - name: Lint container image
        run: make lint-image
  build-image:
    name: Build Image
    needs: prepare
    timeout-minutes: 15
    runs-on: ${{ defaults.os }}
    steps:
      - name: Create cluster with Kind
        run: kind create cluster

      - name: Apply manifests
        run: make apply-manifests

      - name: Build container image
        run: make build-image

      - name: Start port forwarding for container registry
        run: make port-forward &

      - name: Push container image
        run: make push-image

      - name: Waiting for the pod to be ready
        run: |
          while :
          do
            status=$(kubectl --context=kind-kind get pods -o json | jq -r '.items[] | select(.metadata.name | contains("controller")) | .status.phase')
            if [[ $status = 'Running' ]]; then
              break
            fi
            echo 'Waiting for Redis sentinel to be ready...'
            sleep 3
          done

      - name: Print logs of the pod
        run: |
          name=$(kubectl --context=kind-kind get pods -o json | jq -r '.items[] | .metadata.name' | grep controller)
          kubectl --context=kind-kind logs $name
